- copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo
  sudo: true
- yum: name=mongodb-org-server
  sudo: yes
- lineinfile: dest=/etc/mongod.conf regexp=bind_ip=127.0.0.1 line="# bind_ip=127.0.0.1"
  sudo: yes
- service: name=mongod state=started
  sudo: yes
- get_url: url=https://bootstrap.pypa.io/get-pip.py dest=~ mode=0777
- shell: python get-pip.py
  sudo: yes
- pip: name=pymongo
  sudo: yes
- mongodb_user: database=todo name=todo password=todo state=present
