- copy: src=mongodb-org-4.0.repo dest=/etc/yum.repos.d/mongodb-org-4.0.repo
  become: true
  become_user: root
- yum: name=mongodb-org
  become: true
  become_user: root
- service: name=mongod state=started
  become: true
  become_user: root