- copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
  become: true
  become_user: root
- yum: name=nginx
  become: true
  become_user: root
- get_url: url=https://github.com/danielsiwiec/todo-client/archive/master.zip dest=~/frontend.zip
  become: true
  become_user: root
- file: path=/www/data state=directory
  become: true
  become_user: root
- unarchive: src=~/frontend.zip dest=/www/data/ copy=no
  become: true
  become_user: root
- shell: curl -sL https://rpm.nodesource.com/setup | bash -
  become: true
  become_user: root
- yum: name=nodejs
  become: true
  become_user: root
- shell: npm install chdir=/www/data/todo-client-master
  become: true
  become_user: root
- file: path=/etc/nginx/conf.d/ state=absent
  become: true
  become_user: root
- copy: src=todomvc.conf dest=/etc/nginx/conf.d/
  become: true
  become_user: root
- service: name=nginx state=started
  become: true
  become_user: root
